#!/usr/bin/env python3
"""GenEscrow v1.3.0 security video v3: real UI frames + educational captions.

Builds a clean 1920x1080 Ken-Burns base from the captured live-UI frames
(evidence/ui_frames/*.png, which have no burned-in text), then overlays the
detailed educational subtitles. Because the GenEscrow UI is light, the white
caption text sits on a translucent dark bar for legibility. Each caption is
pinned either to the lower third or to the top of the frame (per segment) so it
never covers the specific control it describes.

Usage:
  python scripts/build_security_video_v3.py           # full render
  python scripts/build_security_video_v3.py preview   # draft + overlap-check frames
"""
import os
import pathlib
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
EV = ROOT / "evidence"
FR = EV / "ui_frames"
OUT = EV / "genesrow_security_v3.mp4"
ASS = EV / "genesrow_security_v3.ass"

W, H, FPS = 1920, 1080, 30
FONT = "DejaVu Sans"

# (frame, start, end, heading, [body...], pos)
# pos: "center" = full-frame title card (hero/outro); "top" = caption pinned to
# the top (used when the described control sits low in the frame); "bottom" =
# lower-third caption (used when the described control sits in the upper half).
SEGMENTS = [
    ("01_landing_hero.png", 0, 5, "GenEscrow v1.3.0",
     ["AI-Adjudicated Freelance Escrow", "Security Hardening & Audit Closure",
      "Built on GenLayer StudioNet"], "center"),
    ("04_create_a1_window_error.png", 5, 12, "A1: Window Bounds Validation",
     ["Approve and appeal windows are bounded", "to 60 seconds - 7 days",
      "to prevent indefinite payout stranding"], "bottom"),
    ("10_dispute_prompt.png", 12, 20, "A2: Structural Index Sanitization",
     ["Malicious markup is stripped from", "the delivery index before the LLM prompt",
      "to prevent injection attacks"], "bottom"),
    ("08_deliver_seal.png", 20, 28, "A3: Raw Bytes Seal",
     ["The SHA256 hash covers raw fetched bytes", "(not just cleaned text)",
      "so hidden mutations are caught at audit"], "top"),
    ("05_create_a4_address_error.png", 28, 36, "A4: Freelancer Address Validation",
     ["The contract rejects malformed addresses,", "zero addresses, and addresses matching",
      "the client before any state change"], "bottom"),
    ("07_deliver_allowlist.png", 36, 44, "A5: Gateway Allowlist",
     ["An anchored parser validates evidence URLs", "against 4 allowed gateways",
      "rejecting lookalike hosts and path traversal"], "bottom"),
    ("13_security_reachability.png", 44, 52, "On-Chain Reachability Proof",
     ["Validators independently fetch and verify", "gateway accessibility",
      "proven live on StudioNet"], "bottom"),
    ("15_contract_status.png", 52, 60, "All Changes Verified",
     ["22 mutation-tested Direct Mode tests", "Byte-identical deployed source",
      "Contract: 0x0CF5...c100cE4"], "bottom"),
    ("12_security_a1_a6.png", 60, 68, "GenEscrow v1.3.0",
     ["Security Hardening Complete", "GitHub: github.com/hoveiser/genesrow"], "center"),
]

HEADER = (
    "[Script Info]\n"
    "; generated by scripts/build_security_video_v3.py (UI frames + educational captions)\n"
    "ScriptType: v4.00+\n"
    f"PlayResX: {W}\nPlayResY: {H}\nWrapStyle: 0\nScaledBorderAndShadow: yes\n\n"
    "[V4+ Styles]\n"
    "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, "
    "BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, "
    "BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n"
    # White text on a translucent dark bar (BorderStyle=3). Cap = bottom-center,
    # Top = top-center, Title = middle-center (full-frame hero/outro cards).
    f"Style: Cap,{FONT},42,&H00FFFFFF,&H00FFFFFF,&H00000000,&H64000000,0,0,0,0,100,100,"
    "0,0,3,14,0,2,90,90,70,1\n"
    f"Style: Top,{FONT},42,&H00FFFFFF,&H00FFFFFF,&H00000000,&H64000000,0,0,0,0,100,100,"
    "0,0,3,14,0,8,90,90,70,1\n"
    f"Style: Title,{FONT},60,&H00FFFFFF,&H00FFFFFF,&H00000000,&H64000000,0,0,0,0,100,100,"
    "0,0,3,20,0,5,90,90,90,1\n\n"
    "[Events]\n"
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n"
)

STYLE_FOR_POS = {"center": "Title", "top": "Top", "bottom": "Cap"}


def esc(t):
    return t.replace("\\", "\\\\").replace("{", "\\{").replace("}", "\\}")


def ts(sec):
    return f"{int(sec // 3600)}:{int((sec % 3600) // 60):02d}:{sec % 60:05.2f}"


def caption_text(heading, body):
    parts = [f"{{\\b1\\fs64}}{esc(heading)}{{\\b0\\fs42}}"]
    parts += [esc(b) for b in body]
    return "\\N".join(parts)


def build_ass():
    ev = []
    for _, s, e, heading, body, pos in SEGMENTS:
        style = STYLE_FOR_POS[pos]
        ev.append(f"Dialogue: 0,{ts(s)},{ts(e)},{style},,0,0,0,,{caption_text(heading, body)}\n")
    ASS.write_text(HEADER + "".join(ev))


def run(cmd):
    r = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    if r.returncode != 0:
        print(r.stdout[-3000:])
        sys.exit("ffmpeg failed")


def render_clean_segment(png, dur, outp):
    vf = (
        f"[0:v]scale={W}:{H}:force_original_aspect_ratio=decrease,"
        f"pad={W}:{H}:(ow-iw)/2:(oh-ih)/2:color=0x0b1220,format=yuv420p,"
        f"zoompan=z='min(1+0.0009*on,1.08)':x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)'"
        f":d=1:s={W}x{H}:fps={FPS},fade=t=in:st=0:d=0.4,fade=t=out:st={dur-0.5}:d=0.5,format=yuv420p[v]"
    )
    run(["ffmpeg", "-y", "-hide_banner", "-loglevel", "error", "-loop", "1", "-framerate", str(FPS),
         "-t", str(dur), "-i", str(png), "-filter_complex", vf, "-map", "[v]",
         "-r", str(FPS), "-t", str(dur), "-pix_fmt", "yuv420p", "-c:v", "libx264",
         "-preset", "medium", "-crf", "18", outp])


def build_clean_base(tmp):
    segs = []
    for i, (frame, s, e, *_rest) in enumerate(SEGMENTS):
        dur = e - s
        outp = os.path.join(tmp, f"seg_{i:02d}.mp4")
        render_clean_segment(FR / frame, dur, outp)
        segs.append(outp)
    lst = os.path.join(tmp, "list.txt")
    with open(lst, "w") as f:
        for p in segs:
            f.write(f"file '{p}'\n")
    base = os.path.join(tmp, "clean_base.mp4")
    run(["ffmpeg", "-y", "-hide_banner", "-loglevel", "error", "-f", "concat", "-safe", "0",
         "-i", lst, "-c", "copy", base])
    return base


def render(out):
    build_ass()
    with tempfile.TemporaryDirectory() as tmp:
        base = build_clean_base(tmp)
        run(["ffmpeg", "-y", "-hide_banner", "-loglevel", "error", "-i", base,
             "-vf", f"subtitles={ASS}", "-c:v", "libx264", "-pix_fmt", "yuv420p",
             "-preset", "medium", "-crf", "19", "-r", str(FPS), "-movflags", "+faststart", str(out)])


def grab_frame(src, t, out_png):
    run(["ffmpeg", "-y", "-hide_banner", "-loglevel", "error", "-ss", str(t), "-i", str(src),
         "-frames:v", "1", str(out_png)])


def main():
    if len(sys.argv) > 1 and sys.argv[1] == "preview":
        draft = EV / "genesrow_security_v3_draft.mp4"
        render(draft)
        for t, name in [(8.5, "a1"), (24.0, "seal")]:
            grab_frame(draft, t, EV / f"preview_{name}.png")
        print(f"draft: {draft.name} + preview frames")
        return
    render(OUT)
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size/1e6:.2f} MB, ~{SEGMENTS[-1][2]}s)")


if __name__ == "__main__":
    main()
