#!/usr/bin/env python3
"""Build a captions-only "security hardening" video covering audit closures A1-A5.

Companion to build_video.py (the lifecycle demo). Each segment states one gap and shows
the REAL on-chain result copied from evidence JSON, so nothing is retyped or fabricated:

  * A1 window bounds      from evidence/scenario.json       (a1_ceiling revert)
  * A2 injection          from evidence/scenario.json       (crafted breakout sealed, verdict)
  * A3 raw-byte seal      from evidence/scenario.json       (delivered evidence_hash)
  * A4 address validation from evidence/scenario.json       (a4_zero revert)
  * A5 gateway reachability from evidence/ipfs_gateways.json (control vs three IPFS hosts)
  * byte-identical deploy from evidence/verify_deployment.json (gen_getContractCode)

Captions-only: no headless terminal recorder and no offline text-to-speech exist in this
environment, so there is no voiceover. Requires ffmpeg with libass and DejaVu fonts.
"""
import json
import pathlib
import subprocess

ROOT = pathlib.Path(__file__).resolve().parent.parent
EV = ROOT / "evidence"
OUT = EV / "genesrow_security.mp4"
ASS = EV / "genesrow_security.ass"

W, H, FPS = 1280, 720, 25
MONO = "DejaVu Sans Mono"
SANS = "DejaVu Sans"
SEG = 8.0


def esc(t):
    return t.replace("\\", "\\\\").replace("{", "\\{").replace("}", "\\}")


def ts(sec):
    return f"{int(sec // 3600)}:{int((sec % 3600) // 60):02d}:{sec % 60:04.1f}"


def load():
    sc = json.load(open(EV / "scenario.json"))
    gw = json.load(open(EV / "ipfs_gateways.json"))
    vd = json.load(open(EV / "verify_deployment.json"))
    txs = {t["name"]: t for t in sc["txs"]}
    res = {r["label"]: r for r in gw["results"]}
    return sc, txs, res, vd


def build_segments(sc, txs, res, vd):
    seal = res["CONTROL-raw.github"]["evidence_hash"][:16]
    ipfs = [res[h] for h in ("ipfs.io", "gateway.ipfs.io", "dweb.link")]
    segs = [
        ("A1  Bounded windows (60s to 7 days)",
         [f"create_escrow appeal_window = 10 years",
          f"tx {txs['a1_ceiling']['txid'][:16]}... reverted, total_locked unchanged"]),
        ("A2  Structural-index sanitization",
         [f"crafted breakout artifact delivered",
          f"tx {txs['mark_delivered']['txid'][:16]}... sealed, verdict",
          f"resolve tx {txs['resolve']['txid'][:16]}... = {sc['verdict']['ai_verdict']} (injection did not flip it)"]),
        ("A3  Seal covers raw bytes",
         [f"evidence_hash = sha256(raw bytes)",
          f"sealed {seal}... re-verified by validators"]),
        ("A4  Freelancer address validation",
         [f"create_escrow freelancer = 0x0...0",
          f"tx {txs['a4_zero']['txid'][:16]}... reverted, no escrow created"]),
        ("A5  Gateway allowlist + on-chain reachability",
         [f"raw.githubusercontent: REACHABLE (sealed {seal}...)",
          f"ipfs.io {ipfs[0]['deliver_txid'][:12]}... NOT_REACHABLE",
          f"gateway.ipfs.io {ipfs[1]['deliver_txid'][:12]}... NOT_REACHABLE",
          f"dweb.link {ipfs[2]['deliver_txid'][:12]}... NOT_REACHABLE",
          "all reverted with nondet_disagree=null (unanimous validators)"]),
    ]
    outro = [
        "Deployed source is byte-identical",
        f"{vd['deployed_bytes']} bytes, sha256 {vd['local_sha256'][:16]}... == local contract.py",
    ]
    return segs, outro


HEADER = ("[Script Info]\n"
          "; generated by scripts/build_security_video.py from on-chain evidence JSON\n"
          "ScriptType: v4.00+\n"
          f"PlayResX: {W}\nPlayResY: {H}\nWrapStyle: 0\nScaledBorderAndShadow: yes\n\n"
          "[V4+ Styles]\n"
          "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, "
          "BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, "
          "BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n"
          f"Style: Term,{MONO},17,&H00E6E6E6,&H000000FF,&H00000000,&H80000000,0,0,0,0,100,100,"
          "0,0,1,1,0,7,24,24,120,1\n"
          f"Style: Cap,{SANS},30,&H006BF7FF,&H000000FF,&H00102030,&HAA000000,1,0,0,0,100,100,"
          "0,0,3,2,1,2,1,40,40,40,1\n"
          f"Style: Title,{SANS},48,&H00FFFFFF,&H000000FF,&H001a7a3f,&H80000000,1,0,0,0,100,100,"
          "0,0,1,2,2,5,40,40,40,1\n"
          f"Style: Sub,{SANS},24,&H00CFCFCF,&H000000FF,&H00000000,&H80000000,0,1,0,0,100,100,"
          "0,0,1,1,1,2,40,40,110,1\n\n"
          "[Events]\n"
          "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n")


def main():
    sc, txs, res, vd = load()
    segs, outro = build_segments(sc, txs, res, vd)
    events = []
    t = 0.0
    events.append((t, t + 5.0, "Title", esc("GenEscrow v1.3.0  Security Hardening")))
    events.append((t, t + 5.0, "Sub", esc("each audit closure proven on StudioNet (chain id 61999)")))
    t += 5.5
    for cap, lines in segs:
        start, end = t, t + SEG
        events.append((start, end, "Cap", esc(cap)))
        events.append((start, end, "Term", "\\N".join(esc(l) for l in lines)))
        t = end + 0.3
    events.append((t, t + 5.0, "Title", esc(outro[0])))
    events.append((t, t + 5.0, "Sub", esc(outro[1])))
    total = t + 5.0 + 0.5

    body = "".join(f"Dialogue: 0,{ts(a)},{ts(b)},{sty},,0,0,0,,{txt}\n"
                   for a, b, sty, txt in events)
    ASS.write_text(HEADER + body)

    cmd = ["ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
           "-f", "lavfi", "-i", f"color=c=0x0b1220:s={W}x{H}:r={FPS}:d={total:.1f}",
           "-vf", f"subtitles={ASS}",
           "-c:v", "libx264", "-pix_fmt", "yuv420p", "-preset", "medium", "-crf", "23", str(OUT)]
    print(f"segments: {len(segs)}; video length ~{total:.0f}s")
    subprocess.run(cmd, check=True)
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size/1e6:.2f} MB)")


if __name__ == "__main__":
    main()
