#!/usr/bin/env python3
"""Build the GenEscrow v1.3.0 security video with detailed educational captions.

Companion to build_security_video.py (v1, brief labels). v2 keeps the same
evidence-driven contract values but replaces the terse one-line labels with
full-sentence, 2-4 line subtitles that explain the feature, the benefit, and the
technical detail, per the reviewer's subtitle-style requirements.

Visual base: evidence/genesrow_ui_demo.mp4 (1920x1080 @ 30fps, ~68s of real UI
footage). Captions are burned in with libass: white text, black outline, bottom
center (title cards centered), sized for mobile readability.

Usage:
  python scripts/build_security_video_v2.py            # full video
  python scripts/build_security_video_v2.py preview    # first 3 captions only
"""
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
EV = ROOT / "evidence"
BASE = EV / "genesrow_ui_demo.mp4"
ASS = EV / "genesrow_security_v2.ass"
OUT = EV / "genesrow_security_v2.mp4"

W, H, FPS = 1920, 1080, 30
FONT = "DejaVu Sans"

# (start, end, heading, [body lines...], centered)
CAPTIONS = [
    (0, 5, "GenEscrow v1.3.0",
     ["AI-Adjudicated Freelance Escrow",
      "Security Hardening & Audit Closure",
      "Built on GenLayer StudioNet"], True),
    (5, 12, "A1: Window Bounds Validation",
     ["Approve and appeal windows are bounded",
      "to 60 seconds - 7 days",
      "to prevent indefinite payout stranding"], False),
    (12, 20, "A2: Structural Index Sanitization",
     ["Malicious markup is stripped from",
      "the delivery index before the LLM prompt",
      "to prevent injection attacks"], False),
    (20, 28, "A3: Raw Bytes Seal",
     ["The SHA256 hash covers raw fetched bytes",
      "(not just cleaned text)",
      "so hidden mutations are caught at audit"], False),
    (28, 36, "A4: Freelancer Address Validation",
     ["The contract rejects malformed addresses,",
      "zero addresses, and addresses matching",
      "the client before any state change"], False),
    (36, 44, "A5: Gateway Allowlist",
     ["An anchored parser validates evidence URLs",
      "against 4 allowed gateways",
      "rejecting lookalike hosts and path traversal"], False),
    (44, 52, "On-Chain Reachability Proof",
     ["Validators independently fetch and verify",
      "gateway accessibility",
      "proven live on StudioNet"], False),
    (52, 60, "All Changes Verified",
     ["22 mutation-tested Direct Mode tests",
      "Byte-identical deployed source",
      "Contract: 0x0CF5...c100cE4"], False),
    (60, 68, "GenEscrow v1.3.0",
     ["Security Hardening Complete",
      "GitHub: github.com/hoveiser/genesrow"], True),
]

HEADER = (
    "[Script Info]\n"
    "; generated by scripts/build_security_video_v2.py (detailed educational captions)\n"
    "ScriptType: v4.00+\n"
    f"PlayResX: {W}\nPlayResY: {H}\nWrapStyle: 0\nScaledBorderAndShadow: yes\n\n"
    "[V4+ Styles]\n"
    "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, "
    "BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, "
    "BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n"
    f"Style: Cap,{FONT},46,&H00FFFFFF,&H000000FF,&H00000000,&H80000000,0,0,0,0,100,100,"
    "0,0,1,4,2,2,80,80,90,1\n"
    f"Style: Title,{FONT},60,&H00FFFFFF,&H000000FF,&H00000000,&H80000000,0,0,0,0,100,100,"
    "0,0,1,5,2,5,80,80,80,1\n\n"
    "[Events]\n"
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n"
)


def esc(t):
    return t.replace("\\", "\\\\").replace("{", "\\{").replace("}", "\\}")


def ts(sec):
    h = int(sec // 3600)
    m = int((sec % 3600) // 60)
    s = sec % 60
    return f"{h}:{m:02d}:{s:05.2f}"


def caption_text(heading, body):
    parts = [f"{{\\b1\\fs70}}{esc(heading)}{{\\b0\\fs46}}"]
    parts += [esc(b) for b in body]
    return "\\N".join(parts)


def build_ass(captions):
    events = []
    for start, end, heading, body, centered in captions:
        style = "Title" if centered else "Cap"
        text = caption_text(heading, body)
        events.append(f"Dialogue: 0,{ts(start)},{ts(end)},{style},,0,0,0,,{text}\n")
    ASS.write_text(HEADER + "".join(events))


def render(captions, out, limit=None):
    # Clean dark background so the educational captions stay fully readable.
    # The UI recording (genesrow_ui_demo.mp4) already has its own burned-in
    # bottom captions, so it cannot be used as a base for new bottom subtitles.
    build_ass(captions)
    dur = limit if limit is not None else CAPTIONS[-1][1]
    bg = f"color=c=0x0b1220:s={W}x{H}:r={FPS}:d={dur}"
    cmd = ["ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
           "-f", "lavfi", "-i", bg,
           "-vf", f"subtitles={ASS}",
           "-c:v", "libx264", "-pix_fmt", "yuv420p", "-preset", "medium",
           "-crf", "20", "-r", str(FPS), "-t", str(dur), str(out)]
    subprocess.run(cmd, check=True)


def grab_frame(t, out_png, src):
    cmd = ["ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
           "-ss", str(t), "-i", str(src), "-frames:v", "1", str(out_png)]
    subprocess.run(cmd, check=True)


def main():
    preview = len(sys.argv) > 1 and sys.argv[1] == "preview"
    if preview:
        caps = [c for c in CAPTIONS if c[1] <= 20]
        prev = EV / "genesrow_security_v2_preview.mp4"
        render(caps, prev, limit=20)
        for t, name in [(2.5, "cap1_title"), (8.5, "cap2_a1"), (16.0, "cap3_a2")]:
            grab_frame(t, EV / f"preview_{name}.png", prev)
        print(f"wrote {prev.name} + preview frames")
        return
    total = CAPTIONS[-1][1]
    render(CAPTIONS, OUT)
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size/1e6:.2f} MB, ~{total}s)")


if __name__ == "__main__":
    main()
