#!/usr/bin/env python3
"""Build a captions-only demo video (genesrow_demo.mp4) from the REAL demo transcript.

There is no headless terminal recorder (no asciinema / playwright) and no offline text to
speech in this environment, so this is not a live screen capture and has no voiceover. It is
an honest captions-only render: each timed caption describes a step, and the actual lines of
stdout produced by demo/demo_two_account.py running live against StudioNet (evidence/demo.log)
are shown verbatim on screen, so nothing is fabricated or retyped.

Toolchain actually present and used here: ffmpeg with libass (ASS subtitle burn-in) and the
DejaVu Sans Mono font. Requires: ffmpeg on PATH.
"""
import os
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
LOG = ROOT / "evidence" / "demo.log"
OUT = ROOT / "evidence" / "genesrow_demo.mp4"
ASS = ROOT / "evidence" / "genesrow_captions.ass"

W, H, FPS = 1280, 720, 25
MONO = "DejaVu Sans Mono"
SANS = "DejaVu Sans"


def esc(text: str) -> str:
    # ASS: escape backslash and braces; keep everything else literal
    return text.replace("\\", "\\\\").replace("{", "\\{").replace("}", "\\}")


def ts(sec: float) -> str:
    h = int(sec // 3600)
    m = int((sec % 3600) // 60)
    s = sec % 60
    return f"{h}:{m:02d}:{s:04.1f}"


def load_blocks():
    lines = LOG.read_text().splitlines()
    blocks, cur = [], None
    for ln in lines:
        if ln.startswith("[") and "/5]" in ln:
            cur = [ln.strip()]
            blocks.append(cur)
        elif cur is not None and ln.strip():
            cur.append(ln.strip())
    return blocks


CAPTIONS = [
    "Two independent accounts: a funded client and a fresh, unfunded freelancer",
    "Client funds the escrow with 1 GEN on StudioNet",
    "Delivery submitted: the raw, pinned artifact is sealed by content hash",
    "Client requests an AI review: real validators re-fetch and re-seal",
    "AI arbitration reaches a verdict: independent validators agree APPROVED",
    "Funds released on chain: the fresh freelancer balance goes 0 to 1 GEN",
]

HEADER = ("[Script Info]\n"
          "; generated by scripts/build_video.py from evidence/demo.log (real transcript)\n"
          "ScriptType: v4.00+\n"
          f"PlayResX: {W}\nPlayResY: {H}\nWrapStyle: 0\nScaledBorderAndShadow: yes\n\n"
          "[V4+ Styles]\n"
          "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, "
          "BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, "
          "BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n"
          f"Style: Term,{MONO},17,&H00E6E6E6,&H000000FF,&H00000000,&H80000000,0,0,0,0,100,100,"
          "0,0,1,1,0,7,24,24,24,1\n"
          f"Style: Cap,{SANS},26,&H006BF7FF,&H000000FF,&H00102030,&HAA000000,1,0,0,0,100,100,"
          "0,0,3,2,1,2,2,40,40,54,1\n"
          f"Style: Title,{SANS},52,&H00FFFFFF,&H000000FF,&H001a7a3f,&H80000000,1,0,0,0,100,100,"
          "0,0,1,2,2,5,40,40,40,1\n"
          f"Style: Sub,{SANS},26,&H00CFCFCF,&H000000FF,&H00000000,&H80000000,0,1,0,0,100,100,"
          "0,0,1,1,1,2,40,40,120,1\n\n"
          "[Events]\n"
          "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n")

events = []
t = 0.0
TITLE_S, TITLE_E = t, t + 5.0
events.append((TITLE_S, TITLE_E, "Title", "GenEscrow  intelligent escrow, settled by AI consensus"))
events.append((TITLE_S, TITLE_E, "Sub", "live two-account demo on GenLayer StudioNet (chain id 61999)"))
t = TITLE_E + 0.5

blocks = load_blocks()
DUR = 11.0
for i, block in enumerate(blocks):
    cap = CAPTIONS[min(i + 1, len(CAPTIONS) - 1)] if i < len(CAPTIONS) - 1 else CAPTIONS[-1]
    start, end = t, t + DUR
    term = "\\N".join(esc(l) for l in block)
    events.append((start, end, "Term", term))
    events.append((start, end, "Cap", esc(cap)))
    t = end + 0.3

events.append((t, t + 6.0, "Title", "Funds released on chain"))
events.append((t, t + 6.0, "Sub", "escrow settled to a real GEN balance change for the winner"))
total = t + 6.0 + 0.5

body = "".join(
    f"Dialogue: 0,{ts(a)},{ts(b)},{sty},,0,0,0,,{txt}\n"
    for a, b, sty, txt in events)
ASS.write_text(HEADER + body)

cmd = [
    "ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
    "-f", "lavfi", "-i", f"color=c=0x0b1220:s={W}x{H}:r={FPS}:d={total:.1f}",
    "-vf", f"subtitles={ASS}",
    "-c:v", "libx264", "-pix_fmt", "yuv420p", "-preset", "medium", "-crf", "23",
    str(OUT),
]
print(f"transcript blocks: {len(blocks)}; video length ~{total:.0f}s")
print("running:", " ".join(cmd[:6]), "... (ffmpeg subtitles burn-in)")
subprocess.run(cmd, check=True)
size = OUT.stat().st_size
print(f"wrote {OUT.relative_to(ROOT)} ({size/1e6:.2f} MB)")
